# Generated by Django 5.2.13 on 2026-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_average_rating_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
