# Generated by Django 5.2.13 on 2026-05-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uservector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to=settings.AUTH_USER_MODEL),
        ),
    ]
