# Generated by Django 5.2.13 on 2026-05-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_remove_vendor_is_verified_alter_vendor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
