# Generated by Django 5.2.13 on 2026-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0004_vendor_rejection_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["-created_at"]},
        ),
    ]
